name: rlydoe
channels:
  - pytorch
  - defaults
dependencies:
  - appdirs=1.4.4
  - attrs=20.3.0
  - black=19.10b0
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - click=7.1.2
  - freetype=2.10.4
  - intel-openmp=2019.4
  - jpeg=9b
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuv=1.40.0
  - lz4-c=1.9.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - ninja=1.10.1
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pathspec=0.7.0
  - pillow=8.0.1
  - pip=20.2.4
  - python=3.8.5
  - pytorch=1.7.0
  - readline=8.0
  - regex=2020.10.15
  - setuptools=50.3.1
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - astunparse==1.6.3
    - atari-py==0.2.6
    - box2d-py==2.3.8
    - cachetools==4.1.1
    - chardet==3.0.4
    - cloudpickle==1.6.0
    - configparser==5.0.1
    - cycler==0.10.0
    - dataclasses==0.6
    - docker-pycreds==0.4.0
    - fire==0.3.1
    - future==0.18.2
    - gast==0.3.3
    - gitdb==4.0.5
    - gitpython==3.1.11
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.33.2
    - gym==0.17.3
    - h5py==2.10.0
    - idna==2.10
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.3
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opencv-python==4.4.0.46
    - opt-einsum==3.3.0
    - pandas==1.1.4
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.14.0
    - psutil==5.7.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.0.6
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pyyaml==5.3.1
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.4
    - seaborn==0.11.0
    - sentry-sdk==0.19.4
    - shortuuid==1.0.1
    - smmap==3.0.4
    - stable-baselines3==0.10.0
    - subprocess32==3.5.4
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.3.1
    - tensorflow-estimator==2.3.0
    - termcolor==1.1.0
    - tqdm==4.52.0
    - urllib3==1.26.2
    - wandb==0.10.11
    - watchdog==0.10.3
    - werkzeug==1.0.1
    - wrapt==1.12.1
